
vscode:
  extensions:
    - ms-python.python
    - Vue.volar

ports:
  - port: 3000
    visibility: public
  - port: 5050
    visibility: public
  - port: 8000
    visibility: public
    onOpen: open-browser